version: 2.1

orbs:
  android: circleci/android@2.4.0

jobs:
  build:
    docker:
      - image: cimg/android:2023.11.1
    steps:
      - checkout

      # Restore Gradle cache
      - restore_cache:
          keys:
            - gradle-cache-v1-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-cache-v1-

      # Set file permissions for gradlew
      - run:
          name: Set Gradle Wrapper Permissions
          command: chmod +x ./gradlew

      # Create local.properties file
      - run:
          name: Create Local Properties
          command: echo "sdk.dir=$ANDROID_HOME" > local.properties

      # Accept Android SDK Licenses
      - run:
          name: Accept Android SDK Licenses
          command: yes | sdkmanager --licenses || true

      # Download dependencies
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies

      # Save Gradle cache
      - save_cache:
          paths:
            - ~/.gradle/caches/
            - ~/.gradle/wrapper/
          key: gradle-cache-v1-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      # Build project
      - run:
          name: Run Build
          command: ./gradlew assembleDebug

      # Store build artifacts
      - store_artifacts:
          path: app/build/reports
          destination: reports

      # Run lint and tests
      - run:
          name: Run Lint and Tests
          command: ./gradlew lintDebug testDebugUnitTest

      # Store test results
      - store_test_results:
          path: app/build/test-results

      # Store APK artifact
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apk-debug

workflows:
  version: 2
  build:
    jobs:
      - build
